
export enum PageIdentity {
    Home,
    SourceSelection,
    Era,
    ToolSelection,
    CharacterType,
    Species,
    SpeciesDetails,
    CustomSpeciesDetails,
    KobaliExtraSpeciesDetails,
    BorgSpeciesExtraDetails,
    LiberatedBorgSpeciesExtraDetails,
    CyberneticallyEnhancedSpeciesExtraDetails,
    Environment,
    EnvironmentDetails,
    Upbringing,
    UpbringingDetails,
    Education,
    EducationDetails,
    CareerLength,
    CadetCareer,
    CadetSeniority,
    ChildCareer,
    ChildEducationPage,
    ChildEducationDetailsPage,
    CareerLengthDetails,
    CareerEvent1,
    CareerEvent1Details,
    CareerEvent2,
    CareerEvent2Details,
    AttributesAndDisciplines,
    ExtraTalentDetails,
    Finish,

    CustomSpaceframe,
    MissionProfileTalentSelection,
    MissionProfileSelection,
    MissionPodSelection,
    SimpleStarship,
    SmallCraftStats,
    SpaceframeOption,
    SpaceframeSelection,
    StarshipRefits,
    StarshipToolSelection,
    StarshipTypeSelection,
    StarshipTalentSelection,
    StarshipWeaponsSelection,
    ExpandedMunitionsWeaponsSelection,
    FinalStarshipDetails,
    SupportingCharacter,
    TalentsOverview,

    SystemGeneration,
    SectorDetails,
    StarSystemDetails,

    CreditsPage,
    ViewSheet,

    GamemasterTrackerPage,
    XmlViewer,

    ModificationTypeSelection,
    ReputationChange,
    Promotion,
    NormalMilestone,
    ModificationCompletePage,

    NpcConfiguration,
    TokenCreationPage,

    SoloConstructType,
    SoloCharacterEra,
    SoloSpecies,
    SoloSpeciesDetails,
    SoloEarlyOutlook,
    SoloEarlyOutlookDetails,
    SoloEducationType,
    SoloEducationPage,
    SoloEducationDetailsPage,
    SoloCareerLengthDetails,
    SoloCareerEvent1,
    SoloCareerEventDetails1,
    SoloCareerEvent2,
    SoloCareerEventDetails2,
    SoloFinishingTouches,
    SoloFinal,

    TableList,
    ViewTable,



}
