
export enum PageIdentity {
    Selection,
    Era,
    ToolSelecton,
    CharacterType,
    Species,
    SpeciesDetails,
    KobaliExtraSpeciesDetails,
    Environment,
    EnvironmentDetails,
    Upbringing,
    UpbringingDetails,
    StarfleetAcademy,
    StarfleetAcademyDetails,
    Career,
    CadetCareer,
    CadetSeniority,
    ChildCareer,
    ChildEducationPage,
    ChildEducationDetailsPage,
    CareerDetails,
    CareerEvent1,
    CareerEvent1Details,
    CareerEvent2,
    CareerEvent2Details,
    AttributesAndDisciplines,
    BorgImplants,
    Finish,

    Starship,
    SupportingCharacter,
    TalentsOverview,

    SystemGeneration,
    SectorDetails,
    StarSystemDetails,

    CreditsPage,
    ViewSheet,
}
