
export enum PageIdentity {
    Home,
    Era,
    ToolSelection,
    CharacterType,
    Species,
    SpeciesDetails,
    KobaliExtraSpeciesDetails,
    BorgSpeciesExtraDetails,
    LiberatedBorgSpeciesExtraDetails,
    CyberneticallyEnhancedSpeciesExtraDetails,
    Environment,
    EnvironmentDetails,
    Upbringing,
    UpbringingDetails,
    StarfleetAcademy,
    StarfleetAcademyDetails,
    Career,
    CadetCareer,
    CadetSeniority,
    ChildCareer,
    ChildEducationPage,
    ChildEducationDetailsPage,
    CareerDetails,
    CareerEvent1,
    CareerEvent1Details,
    CareerEvent2,
    CareerEvent2Details,
    AttributesAndDisciplines,
    BorgImplants,
    ExtraFocus,
    Finish,

    CustomSpaceframe,
    MissionProfileTalentSelection,
    MissionProfileSelection,
    MissionPodSelection,
    SimpleStarship,
    SmallCraftStats,
    SpaceframeOption,
    SpaceframeSelection,
    Starship,
    StarshipRefits,
    StarshipToolSelection,
    StarshipTypeSelection,
    StarshipTalentSelection,
    StarshipWeaponsSelection,
    FinalStarshipDetails,
    SupportingCharacter,
    TalentsOverview,

    SystemGeneration,
    SectorDetails,
    StarSystemDetails,

    CreditsPage,
    ViewSheet,

    GamemasterTrackerPage
}
